services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${SERVER_DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${SERVER_DATABASE_USER}
      POSTGRES_PASSWORD: ${SERVER_DATABASE_PASSWORD}
      POSTGRES_DB: ${SERVER_DATABASE_NAME}
    volumes:
      - db:/var/lib/postgres/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - ${PGADMING_PORT:-8081}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMING_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_EMAIL_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  db:
    driver: local
  pgadmin:
    driver: local